# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /run/media/ikidd/Data/Distrobox/Ktailctl/KTailctl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /run/media/ikidd/Data/Distrobox/Ktailctl/KTailctl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"ktailctl\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /run/media/ikidd/Data/Distrobox/Ktailctl/KTailctl/CMakeFiles /run/media/ikidd/Data/Distrobox/Ktailctl/KTailctl//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /run/media/ikidd/Data/Distrobox/Ktailctl/KTailctl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named fetch-translations

# Build rule for target.
fetch-translations: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fetch-translations
.PHONY : fetch-translations

# fast build rule for target.
fetch-translations/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fetch-translations.dir/build.make CMakeFiles/fetch-translations.dir/build
.PHONY : fetch-translations/fast

#=============================================================================
# Target rules for targets named KF6Config_QCH

# Build rule for target.
KF6Config_QCH: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 KF6Config_QCH
.PHONY : KF6Config_QCH

# fast build rule for target.
KF6Config_QCH/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KF6Config_QCH.dir/build.make CMakeFiles/KF6Config_QCH.dir/build
.PHONY : KF6Config_QCH/fast

#=============================================================================
# Target rules for targets named KF6CoreAddons_QCH

# Build rule for target.
KF6CoreAddons_QCH: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 KF6CoreAddons_QCH
.PHONY : KF6CoreAddons_QCH

# fast build rule for target.
KF6CoreAddons_QCH/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KF6CoreAddons_QCH.dir/build.make CMakeFiles/KF6CoreAddons_QCH.dir/build
.PHONY : KF6CoreAddons_QCH/fast

#=============================================================================
# Target rules for targets named KF6GuiAddons_QCH

# Build rule for target.
KF6GuiAddons_QCH: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 KF6GuiAddons_QCH
.PHONY : KF6GuiAddons_QCH

# fast build rule for target.
KF6GuiAddons_QCH/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KF6GuiAddons_QCH.dir/build.make CMakeFiles/KF6GuiAddons_QCH.dir/build
.PHONY : KF6GuiAddons_QCH/fast

#=============================================================================
# Target rules for targets named KF6I18n_QCH

# Build rule for target.
KF6I18n_QCH: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 KF6I18n_QCH
.PHONY : KF6I18n_QCH

# fast build rule for target.
KF6I18n_QCH/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KF6I18n_QCH.dir/build.make CMakeFiles/KF6I18n_QCH.dir/build
.PHONY : KF6I18n_QCH/fast

#=============================================================================
# Target rules for targets named KF6Notifications_QCH

# Build rule for target.
KF6Notifications_QCH: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 KF6Notifications_QCH
.PHONY : KF6Notifications_QCH

# fast build rule for target.
KF6Notifications_QCH/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KF6Notifications_QCH.dir/build.make CMakeFiles/KF6Notifications_QCH.dir/build
.PHONY : KF6Notifications_QCH/fast

#=============================================================================
# Target rules for targets named all_aotstats

# Build rule for target.
all_aotstats: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_aotstats
.PHONY : all_aotstats

# fast build rule for target.
all_aotstats/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_aotstats.dir/build.make CMakeFiles/all_aotstats.dir/build
.PHONY : all_aotstats/fast

#=============================================================================
# Target rules for targets named ktailctl

# Build rule for target.
ktailctl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ktailctl
.PHONY : ktailctl

# fast build rule for target.
ktailctl/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/ktailctl.dir/build.make src/CMakeFiles/ktailctl.dir/build
.PHONY : ktailctl/fast

#=============================================================================
# Target rules for targets named ktailctl_autogen

# Build rule for target.
ktailctl_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ktailctl_autogen
.PHONY : ktailctl_autogen

# fast build rule for target.
ktailctl_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/ktailctl_autogen.dir/build.make src/CMakeFiles/ktailctl_autogen.dir/build
.PHONY : ktailctl_autogen/fast

#=============================================================================
# Target rules for targets named ktailctl_data

# Build rule for target.
ktailctl_data: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ktailctl_data
.PHONY : ktailctl_data

# fast build rule for target.
ktailctl_data/fast:
	$(MAKE) $(MAKESILENT) -f src/data/CMakeFiles/ktailctl_data.dir/build.make src/data/CMakeFiles/ktailctl_data.dir/build
.PHONY : ktailctl_data/fast

#=============================================================================
# Target rules for targets named ktailctl_data_autogen

# Build rule for target.
ktailctl_data_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ktailctl_data_autogen
.PHONY : ktailctl_data_autogen

# fast build rule for target.
ktailctl_data_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/data/CMakeFiles/ktailctl_data_autogen.dir/build.make src/data/CMakeFiles/ktailctl_data_autogen.dir/build
.PHONY : ktailctl_data_autogen/fast

#=============================================================================
# Target rules for targets named ktailctl_config

# Build rule for target.
ktailctl_config: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ktailctl_config
.PHONY : ktailctl_config

# fast build rule for target.
ktailctl_config/fast:
	$(MAKE) $(MAKESILENT) -f src/config/CMakeFiles/ktailctl_config.dir/build.make src/config/CMakeFiles/ktailctl_config.dir/build
.PHONY : ktailctl_config/fast

#=============================================================================
# Target rules for targets named ktailctl_config_autogen

# Build rule for target.
ktailctl_config_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ktailctl_config_autogen
.PHONY : ktailctl_config_autogen

# fast build rule for target.
ktailctl_config_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/config/CMakeFiles/ktailctl_config_autogen.dir/build.make src/config/CMakeFiles/ktailctl_config_autogen.dir/build
.PHONY : ktailctl_config_autogen/fast

#=============================================================================
# Target rules for targets named ktailctl_taildrop

# Build rule for target.
ktailctl_taildrop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ktailctl_taildrop
.PHONY : ktailctl_taildrop

# fast build rule for target.
ktailctl_taildrop/fast:
	$(MAKE) $(MAKESILENT) -f src/taildrop/CMakeFiles/ktailctl_taildrop.dir/build.make src/taildrop/CMakeFiles/ktailctl_taildrop.dir/build
.PHONY : ktailctl_taildrop/fast

#=============================================================================
# Target rules for targets named ktailctl_taildrop_autogen

# Build rule for target.
ktailctl_taildrop_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ktailctl_taildrop_autogen
.PHONY : ktailctl_taildrop_autogen

# fast build rule for target.
ktailctl_taildrop_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/taildrop/CMakeFiles/ktailctl_taildrop_autogen.dir/build.make src/taildrop/CMakeFiles/ktailctl_taildrop_autogen.dir/build
.PHONY : ktailctl_taildrop_autogen/fast

#=============================================================================
# Target rules for targets named ktailctl_tailscale

# Build rule for target.
ktailctl_tailscale: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ktailctl_tailscale
.PHONY : ktailctl_tailscale

# fast build rule for target.
ktailctl_tailscale/fast:
	$(MAKE) $(MAKESILENT) -f src/tailscale/CMakeFiles/ktailctl_tailscale.dir/build.make src/tailscale/CMakeFiles/ktailctl_tailscale.dir/build
.PHONY : ktailctl_tailscale/fast

#=============================================================================
# Target rules for targets named ktailctl_tailscale_autogen

# Build rule for target.
ktailctl_tailscale_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ktailctl_tailscale_autogen
.PHONY : ktailctl_tailscale_autogen

# fast build rule for target.
ktailctl_tailscale_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/tailscale/CMakeFiles/ktailctl_tailscale_autogen.dir/build.make src/tailscale/CMakeFiles/ktailctl_tailscale_autogen.dir/build
.PHONY : ktailctl_tailscale_autogen/fast

#=============================================================================
# Target rules for targets named ktailctl_util

# Build rule for target.
ktailctl_util: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ktailctl_util
.PHONY : ktailctl_util

# fast build rule for target.
ktailctl_util/fast:
	$(MAKE) $(MAKESILENT) -f src/util/CMakeFiles/ktailctl_util.dir/build.make src/util/CMakeFiles/ktailctl_util.dir/build
.PHONY : ktailctl_util/fast

#=============================================================================
# Target rules for targets named ktailctl_util_autogen

# Build rule for target.
ktailctl_util_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ktailctl_util_autogen
.PHONY : ktailctl_util_autogen

# fast build rule for target.
ktailctl_util_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/util/CMakeFiles/ktailctl_util_autogen.dir/build.make src/util/CMakeFiles/ktailctl_util_autogen.dir/build
.PHONY : ktailctl_util_autogen/fast

#=============================================================================
# Target rules for targets named ktailctl_components_plugin

# Build rule for target.
ktailctl_components_plugin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ktailctl_components_plugin
.PHONY : ktailctl_components_plugin

# fast build rule for target.
ktailctl_components_plugin/fast:
	$(MAKE) $(MAKESILENT) -f src/components_plugin/CMakeFiles/ktailctl_components_plugin.dir/build.make src/components_plugin/CMakeFiles/ktailctl_components_plugin.dir/build
.PHONY : ktailctl_components_plugin/fast

#=============================================================================
# Target rules for targets named qt_internal_plugins

# Build rule for target.
qt_internal_plugins: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qt_internal_plugins
.PHONY : qt_internal_plugins

# fast build rule for target.
qt_internal_plugins/fast:
	$(MAKE) $(MAKESILENT) -f src/components_plugin/CMakeFiles/qt_internal_plugins.dir/build.make src/components_plugin/CMakeFiles/qt_internal_plugins.dir/build
.PHONY : qt_internal_plugins/fast

#=============================================================================
# Target rules for targets named ktailctl_components_plugin_qmltyperegistration

# Build rule for target.
ktailctl_components_plugin_qmltyperegistration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ktailctl_components_plugin_qmltyperegistration
.PHONY : ktailctl_components_plugin_qmltyperegistration

# fast build rule for target.
ktailctl_components_plugin_qmltyperegistration/fast:
	$(MAKE) $(MAKESILENT) -f src/components_plugin/CMakeFiles/ktailctl_components_plugin_qmltyperegistration.dir/build.make src/components_plugin/CMakeFiles/ktailctl_components_plugin_qmltyperegistration.dir/build
.PHONY : ktailctl_components_plugin_qmltyperegistration/fast

#=============================================================================
# Target rules for targets named all_qmltyperegistrations

# Build rule for target.
all_qmltyperegistrations: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_qmltyperegistrations
.PHONY : all_qmltyperegistrations

# fast build rule for target.
all_qmltyperegistrations/fast:
	$(MAKE) $(MAKESILENT) -f src/components_plugin/CMakeFiles/all_qmltyperegistrations.dir/build.make src/components_plugin/CMakeFiles/all_qmltyperegistrations.dir/build
.PHONY : all_qmltyperegistrations/fast

#=============================================================================
# Target rules for targets named ktailctl_components_plugin_qmllint

# Build rule for target.
ktailctl_components_plugin_qmllint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ktailctl_components_plugin_qmllint
.PHONY : ktailctl_components_plugin_qmllint

# fast build rule for target.
ktailctl_components_plugin_qmllint/fast:
	$(MAKE) $(MAKESILENT) -f src/components_plugin/CMakeFiles/ktailctl_components_plugin_qmllint.dir/build.make src/components_plugin/CMakeFiles/ktailctl_components_plugin_qmllint.dir/build
.PHONY : ktailctl_components_plugin_qmllint/fast

#=============================================================================
# Target rules for targets named ktailctl_components_plugin_qmllint_json

# Build rule for target.
ktailctl_components_plugin_qmllint_json: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ktailctl_components_plugin_qmllint_json
.PHONY : ktailctl_components_plugin_qmllint_json

# fast build rule for target.
ktailctl_components_plugin_qmllint_json/fast:
	$(MAKE) $(MAKESILENT) -f src/components_plugin/CMakeFiles/ktailctl_components_plugin_qmllint_json.dir/build.make src/components_plugin/CMakeFiles/ktailctl_components_plugin_qmllint_json.dir/build
.PHONY : ktailctl_components_plugin_qmllint_json/fast

#=============================================================================
# Target rules for targets named ktailctl_components_plugin_qmllint_module

# Build rule for target.
ktailctl_components_plugin_qmllint_module: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ktailctl_components_plugin_qmllint_module
.PHONY : ktailctl_components_plugin_qmllint_module

# fast build rule for target.
ktailctl_components_plugin_qmllint_module/fast:
	$(MAKE) $(MAKESILENT) -f src/components_plugin/CMakeFiles/ktailctl_components_plugin_qmllint_module.dir/build.make src/components_plugin/CMakeFiles/ktailctl_components_plugin_qmllint_module.dir/build
.PHONY : ktailctl_components_plugin_qmllint_module/fast

#=============================================================================
# Target rules for targets named all_qmllint

# Build rule for target.
all_qmllint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_qmllint
.PHONY : all_qmllint

# fast build rule for target.
all_qmllint/fast:
	$(MAKE) $(MAKESILENT) -f src/components_plugin/CMakeFiles/all_qmllint.dir/build.make src/components_plugin/CMakeFiles/all_qmllint.dir/build
.PHONY : all_qmllint/fast

#=============================================================================
# Target rules for targets named all_qmllint_json

# Build rule for target.
all_qmllint_json: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_qmllint_json
.PHONY : all_qmllint_json

# fast build rule for target.
all_qmllint_json/fast:
	$(MAKE) $(MAKESILENT) -f src/components_plugin/CMakeFiles/all_qmllint_json.dir/build.make src/components_plugin/CMakeFiles/all_qmllint_json.dir/build
.PHONY : all_qmllint_json/fast

#=============================================================================
# Target rules for targets named all_qmllint_module

# Build rule for target.
all_qmllint_module: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_qmllint_module
.PHONY : all_qmllint_module

# fast build rule for target.
all_qmllint_module/fast:
	$(MAKE) $(MAKESILENT) -f src/components_plugin/CMakeFiles/all_qmllint_module.dir/build.make src/components_plugin/CMakeFiles/all_qmllint_module.dir/build
.PHONY : all_qmllint_module/fast

#=============================================================================
# Target rules for targets named module_ktailctl_components_plugin_aotstats_targets

# Build rule for target.
module_ktailctl_components_plugin_aotstats_targets: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 module_ktailctl_components_plugin_aotstats_targets
.PHONY : module_ktailctl_components_plugin_aotstats_targets

# fast build rule for target.
module_ktailctl_components_plugin_aotstats_targets/fast:
	$(MAKE) $(MAKESILENT) -f src/components_plugin/CMakeFiles/module_ktailctl_components_plugin_aotstats_targets.dir/build.make src/components_plugin/CMakeFiles/module_ktailctl_components_plugin_aotstats_targets.dir/build
.PHONY : module_ktailctl_components_plugin_aotstats_targets/fast

#=============================================================================
# Target rules for targets named ktailctl_components_plugin_tooling

# Build rule for target.
ktailctl_components_plugin_tooling: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ktailctl_components_plugin_tooling
.PHONY : ktailctl_components_plugin_tooling

# fast build rule for target.
ktailctl_components_plugin_tooling/fast:
	$(MAKE) $(MAKESILENT) -f src/components_plugin/CMakeFiles/ktailctl_components_plugin_tooling.dir/build.make src/components_plugin/CMakeFiles/ktailctl_components_plugin_tooling.dir/build
.PHONY : ktailctl_components_plugin_tooling/fast

#=============================================================================
# Target rules for targets named ktailctl_components_plugin_autogen

# Build rule for target.
ktailctl_components_plugin_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ktailctl_components_plugin_autogen
.PHONY : ktailctl_components_plugin_autogen

# fast build rule for target.
ktailctl_components_plugin_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/components_plugin/CMakeFiles/ktailctl_components_plugin_autogen.dir/build.make src/components_plugin/CMakeFiles/ktailctl_components_plugin_autogen.dir/build
.PHONY : ktailctl_components_plugin_autogen/fast

#=============================================================================
# Target rules for targets named ktailctl_wrapper_logging

# Build rule for target.
ktailctl_wrapper_logging: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ktailctl_wrapper_logging
.PHONY : ktailctl_wrapper_logging

# fast build rule for target.
ktailctl_wrapper_logging/fast:
	$(MAKE) $(MAKESILENT) -f src/wrapper/CMakeFiles/ktailctl_wrapper_logging.dir/build.make src/wrapper/CMakeFiles/ktailctl_wrapper_logging.dir/build
.PHONY : ktailctl_wrapper_logging/fast

#=============================================================================
# Target rules for targets named ktailctl_wrapper_target

# Build rule for target.
ktailctl_wrapper_target: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ktailctl_wrapper_target
.PHONY : ktailctl_wrapper_target

# fast build rule for target.
ktailctl_wrapper_target/fast:
	$(MAKE) $(MAKESILENT) -f src/wrapper/CMakeFiles/ktailctl_wrapper_target.dir/build.make src/wrapper/CMakeFiles/ktailctl_wrapper_target.dir/build
.PHONY : ktailctl_wrapper_target/fast

#=============================================================================
# Target rules for targets named ktailctl_wrapper_logging_autogen

# Build rule for target.
ktailctl_wrapper_logging_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ktailctl_wrapper_logging_autogen
.PHONY : ktailctl_wrapper_logging_autogen

# fast build rule for target.
ktailctl_wrapper_logging_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/wrapper/CMakeFiles/ktailctl_wrapper_logging_autogen.dir/build.make src/wrapper/CMakeFiles/ktailctl_wrapper_logging_autogen.dir/build
.PHONY : ktailctl_wrapper_logging_autogen/fast

#=============================================================================
# Target rules for targets named test_data

# Build rule for target.
test_data: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_data
.PHONY : test_data

# fast build rule for target.
test_data/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_data.dir/build.make tests/CMakeFiles/test_data.dir/build
.PHONY : test_data/fast

#=============================================================================
# Target rules for targets named test_data_autogen

# Build rule for target.
test_data_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_data_autogen
.PHONY : test_data_autogen

# fast build rule for target.
test_data_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_data_autogen.dir/build.make tests/CMakeFiles/test_data_autogen.dir/build
.PHONY : test_data_autogen/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... KF6Config_QCH"
	@echo "... KF6CoreAddons_QCH"
	@echo "... KF6GuiAddons_QCH"
	@echo "... KF6I18n_QCH"
	@echo "... KF6Notifications_QCH"
	@echo "... all_aotstats"
	@echo "... all_qmllint"
	@echo "... all_qmllint_json"
	@echo "... all_qmllint_module"
	@echo "... all_qmltyperegistrations"
	@echo "... fetch-translations"
	@echo "... ktailctl_autogen"
	@echo "... ktailctl_components_plugin_autogen"
	@echo "... ktailctl_components_plugin_qmllint"
	@echo "... ktailctl_components_plugin_qmllint_json"
	@echo "... ktailctl_components_plugin_qmllint_module"
	@echo "... ktailctl_components_plugin_qmltyperegistration"
	@echo "... ktailctl_config_autogen"
	@echo "... ktailctl_data_autogen"
	@echo "... ktailctl_taildrop_autogen"
	@echo "... ktailctl_tailscale_autogen"
	@echo "... ktailctl_util_autogen"
	@echo "... ktailctl_wrapper_logging_autogen"
	@echo "... ktailctl_wrapper_target"
	@echo "... module_ktailctl_components_plugin_aotstats_targets"
	@echo "... qt_internal_plugins"
	@echo "... test_data_autogen"
	@echo "... uninstall"
	@echo "... ktailctl"
	@echo "... ktailctl_components_plugin"
	@echo "... ktailctl_components_plugin_tooling"
	@echo "... ktailctl_config"
	@echo "... ktailctl_data"
	@echo "... ktailctl_taildrop"
	@echo "... ktailctl_tailscale"
	@echo "... ktailctl_util"
	@echo "... ktailctl_wrapper_logging"
	@echo "... test_data"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

