// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef TAILCTL_VERSION_H
#define TAILCTL_VERSION_H

#define TAILCTL_VERSION_STRING "0.1"
#define TAILCTL_VERSION_MAJOR 0.1
#define TAILCTL_VERSION_MINOR 0.1
#define TAILCTL_VERSION_PATCH 0.1
#define TAILCTL_VERSION ((0.1<<16)|(0.1<<8)|(0.1))

#endif
